### ISSUE TITLE
[TicTacToe] Лишние файлы

### ISSUE THREAD

**Issue by pavel-b-novikov** [NikitaSarin/nsudotnet#1]
/bin/ не должно быть в git-репозитории

**Comment by NikitaSarin** [comment]
добавил в gitignore

**Comment by pavel-b-novikov** [comment]
И obj тоже.
И вообще - возьмите у кого-нибудь из товарищей шаблон .gitignore для VS.

**Comment by NikitaSarin** [comment]
исправил
