### ISSUE TITLE
[TicTacToe] MVVM

### ISSUE THREAD

**Issue by pavel-b-novikov** [NikitaSarin/nsudotnet#2]
Вы сделали ViewModel? В консольном-то приложении? А вы хотя бы знаете что такое MVVM и зачем он нужен?

**Comment by NikitaSarin** [comment]
Знаю, здесь ViewModel выступает в качестве прослойки между View и Model, подготавливая данные для отображения в первом и изменяет их во втором. Сделал по привычке, тк работаю IOS-разработчиком и обычно использую такую архитектуру, так что здесь MVVM именно в понимании Эпла(без биндинга и тд). MVC как то ну совсем мне не близок - слишком близко все сущности друг к другу, но приложение с архитиктурой - всегда намного лучше - поэтому сделал так. Извиняюсь, если оскорбил чьи то чувства:)

**Comment by pavel-b-novikov** [comment]
Видите ли в чем дело - смысл задачи в том, чтобы в дальнейшем использовать её как основу для графического UI. То есть фактически нужно реализовать всю логику, с отделяемой консольной частью чтобы вместо неё прикрутить WPF. Ваша реализация едва ли соответствует таким требованиям. Разнесите, пожалуйста, так чтобы был нормальный API

**Comment by NikitaSarin** [comment]
сделал, убрал парсинг во вью, модель больше не возвращает строки и умеет только пытаться поставить крестик или нолик, возвращая результат

**Comment by NikitaSarin** [comment]
*вьюмодель, извиняюсь

**Comment by pavel-b-novikov** [comment]
Пойдет
